defaults:
  - model: gpt2
  - training: default
  - _self_

# Project configuration
project:
  name: model_tuning
  seed: 42
  device: auto  # Will automatically detect GPU/CPU
  save_strategy: "steps"
  save_steps: 1000
  evaluation_strategy: "steps"
  eval_steps: 500

# Paths configuration
paths:
  data_dir: ${hydra:runtime.cwd}/data
  raw_data: ${paths.data_dir}/raw
  processed_data: ${paths.data_dir}/processed
  model_dir: ${hydra:runtime.cwd}/models
  output_dir: ${hydra:runtime.cwd}/outputs
  log_dir: ${paths.output_dir}/logs

# Weights & Biases configuration
wandb:
  project: ${project.name}
  entity: ${oc.env:WANDB_ENTITY}
  mode: online  # Set to "disabled" to turn off
  tags: []

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  to_file: true
  filename: ${paths.log_dir}/experiment.log

# Runtime configuration
runtime:
  mixed_precision: "fp16"
  gradient_checkpointing: false
  distributed_training: false

hydra:
  run:
    dir: ${paths.output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${paths.output_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true
